version: 0.7.0.{build}
configuration: Release

skip_tags: true

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: off

build_script:
- ps: .\build.ps1 Package All

artifacts:
- path: build\packages\**\*.nupkg
  name: NuGet

hosts:
  api.nuget.org: 93.184.221.200
  dotnetcli.azureedge.net:  93.184.221.200